# Generated by Django 4.2.8 on 2024-10-23 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название ингредиента')),
                ('calories', models.PositiveIntegerField(blank=True, null=True, verbose_name='Калории')),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_limit', models.CharField(max_length=200, verbose_name='Временной лимит')),
                ('breakfast', models.BooleanField(default=False, verbose_name='Есть завтрак?')),
                ('dinner', models.BooleanField(default=False, verbose_name='Есть обед?')),
                ('supper', models.BooleanField(default=False, verbose_name='Есть ужин?')),
                ('dessert', models.BooleanField(default=False, verbose_name='Есть десерт?')),
                ('allergies', models.TextField(choices=[('none', 'Нет аллергий'), ('seafood', 'Рыба и морепродукты'), ('meat', 'Мясо'), ('grains', 'Зерновые'), ('honey', 'Продукты пчеловодства'), ('nuts', 'Орехи и бобовые'), ('dairy', 'Молочные продукты')], default='none', max_length=20, verbose_name='Аллергии')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя клиента')),
                ('tariff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.tariff', verbose_name='Тариф')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название рецепта')),
                ('description', models.TextField(blank=True, verbose_name='Описание рецепта')),
                ('image', models.ImageField(upload_to='recipes/img', verbose_name='Картинка с рецептом')),
                ('ingredients', models.ManyToManyField(to='recipes.ingredient', verbose_name='Ингредиенты')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
            },
        ),
    ]
