# Generated by Django 4.2.8 on 2024-10-26 12:59

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_recipes_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='description',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Описание рецепта'),
        ),
    ]
