# Generated by Django 4.2.8 on 2024-10-26 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_recipeingredient_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tariff',
            name='allergies',
        ),
        migrations.RemoveField(
            model_name='tariff',
            name='breakfast',
        ),
        migrations.RemoveField(
            model_name='tariff',
            name='dessert',
        ),
        migrations.RemoveField(
            model_name='tariff',
            name='dinner',
        ),
        migrations.RemoveField(
            model_name='tariff',
            name='supper',
        ),
        migrations.AddField(
            model_name='recipes',
            name='publication',
            field=models.CharField(choices=[('Published', 'Опубликовано'), ('archived', 'В архиве')], default='archived', max_length=20, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='time_limit',
            field=models.CharField(max_length=20, verbose_name='Временной лимит'),
        ),
    ]
