# Generated by Django 4.2.8 on 2024-10-27 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_remove_tariff_allergies_remove_tariff_breakfast_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание рецепта'),
        ),
    ]
